name: SL Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v2

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        type: php

    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports
